"""
Title: Find the Difference
URL: https://leetcode.com/problems/find-the-difference/description/
Difficulty: Easy
Tags: Google, Meta, Microsoft, Apple, Amazon, Bloomberg
Topics: Hash Table
String
Bit Manipulation
Sorting

Approach:
- just make counters and use t's counter to check if count is unequal or if not present in s
- random character can be added, not just characters found in s


Time Complexity: O(m + n)
Space Complexity: O(m + n)



Solution:
"""
from template import *

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s_counts = defaultdict(int)
        t_counts = defaultdict(int)

        for c in s:
            s_counts[c] += 1
        
        for c in t:
            t_counts[c] += 1
        
        for key in t_counts:
            if t_counts[key] != s_counts[key] or key not in s_counts:
                return key



"""
Question:

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""